[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
ticket_fields = { path = "../../../helpers/ticket_fields" }
thiserror = {version = "2"}
anyhow = { version = "1" }
tokio = { version = "1", features = ["full"] }
axum = "0.8.6"

